version: "3.5"
services:
  hello_world:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        API_PORT: ${API_PORT-8000}
    ports:
      - ${API_PORT-8000}:${API_PORT-8000}
    environment:
      API_PORT: ${API_PORT-8000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT-8000}"]
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - api

  hello_world_tests:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      API_PORT: "${API_PORT-8000}"
      API_HOST: hello_world
    command: ["pytest", "hello_world_tests"]
    depends_on:
      - hello_world
    networks:
      - api

networks:
  api:
    name: simple-falcon-api
    driver: bridge
